---
title: "Co2-emission-exploration"
author: "Stephanie Hutson"
date: "October 4, 2015"
output: html_document
---

```{r echo=FALSE}
  # install.packages('ggplot2')
  # install.packages('plyr')
  library(ggplot2)
```
Here I will explore co2 emission over 193 countries between 1996 and 2010 
```{r}
  carbonData <- read.csv('co2-world-data.csv', header=T )
  
  plot(carbonData$Country.Name, carbonData$X1996..YR1996.) 
  #a basic scatter plot representing the co2 emissions from 
  ggplot(data=carbonData, aes(X2010..YR2010., X1996..YR1996.)) +
    geom_point(color='blue', size=4) +
    ggtitle("Comparing 1996 with 2010") +
    theme(plot.title = element_text(face='bold')) +
    xlab('2010') +
    ylab('1996') +
    geom_abline(data = lm(carbonData$X1996..YR1996. ~ carbonData$X2010..YR2010.))

  
  summary(carbonData$X1996..YR1996.)
  summary(carbonData$X2010..YR2010.)
  cor.test(carbonData$X1996..YR1996., carbonData$X2010..YR2010.)
    
```

Now let's checkout some boxplots

```{r}
  ggplot(data=carbonData, aes('1996', X1996..YR1996.)) +
    geom_boxplot() +
    ylim(0,20) +
    ylab("Metric Tonnes per Capita") +
    ggtitle("1996 boxplot, removing outliers")
  
  ggplot(data=carbonData, aes('2010', X2010..YR2010.)) +
    geom_boxplot() +
    ylim(0,20) +
    ylab("Metric Tonnes per Capita") +
    ggtitle("2010 boxplot, removoing outliers")
    
```

But that's not very meaning full. Let's put them next to each other

```{r}
  library(ggplot2)
  just1996 <- subset(carbonData, select=c(X1996..YR1996.))
  just2010 <- subset(carbonData, select=c(X2010..YR2010.))
  twoYears <- data.frame(yearGroup = c(carbonData$X1996..YR1996., carbonData$X2010..YR2010.), year=c("1996","2010"))
  
  plot1996 <- ggplot(data=just1996, aes('1996', X1996..YR1996.)) + 
    geom_boxplot()
  
  plot2010 <- ggplot(data=just2010, aes('2010', X2010..YR2010.)) + 
    geom_boxplot()
  
  ggplot(data=twoYears, aes(twoYears$year, twoYears$yearGroup)) +
    geom_boxplot() + 
    coord_trans(ytrans = "sqrt")
    
  
```




<b>Sources:</b>
The data for this exploration comes from The World Bank.
http://data.worldbank.org/indicator/EN.ATM.CO2E.PC