---
title: "Carbon Dioxide Emission Exploration"
author: "Stephanie Hutson"
date: "October 5, 2015"
output: html_document
runtime: shiny
---



```{r, echo=FALSE, comment="Notes from rendering:"}
source("responsiveMaps/helpers.R")
```
###Select the year you are interested in exploring.
```{r echo=FALSE}
inputPanel(
  
  sliderInput("year", label = "Year",
              min = 1996, max = 2011, value = 2011),
  renderTable(emission_table(year = input$year))
  
)
renderPlot({
  par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
  plotOutput(emission_map(var = data, legend.title = input$year)  , width="100%", height = "900px")
  
})
```

```{r echo=F}
fluidRow(
  column(5,
         h3(paste("The worst offenders")
            ),
         renderTable(worst_offenders_table(year=input$year))
  ),
  column(7,
         renderPlot(allNationsPlot(year=input$year))
         )
)


```
Source:
All data comes from The World Bank (http://data.worldbank.org/indicator/EN.ATM.CO2E.PC)
CO2 emission units in are metric tonnes per capita